name: "Feature Request"
description: "Request a new feature."
title: "[Feature] <short description>"
labels: ["feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Describe the new feature and why it should be added.

  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      placeholder: "What problem does this feature address?"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: "Describe the feature in detail"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: "Other solutions you've tried or considered"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      placeholder: "Mockups, references, links..."
    validations:
      required: false
