name: "Feature Request"
description: "Request a new feature or capability."
title: "[Feature] <short description>"
labels: ["feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe your feature in clear and structured detail.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What feature do you want to add and why?
      placeholder: |
        Explain the feature and the problem it solves.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Define measurable conditions that must be met.
      placeholder: |
        - AC1: ...
        - AC2: ...
        - AC3: ...
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure all items are completed.
      options:
        - label: I have checked for duplicate issues.
        - label: I have provided a clear feature description.
        - label: I have defined acceptance criteria.
        - label: I believe this feature fits the project scope.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Notes
      description: Add mockups, references, or context.
      placeholder: "Optional: diagrams, links, screenshots..."
    validations:
      required: false
